/*
Custom Nextflow module to parse an Illumina format SampleSheet.csv

Input:
  -- samplesheetnextflow: version of samplesheet generated by PARSE_SAMPLESHEET that includes a column majiq_group

Output:
  -- majiq_settings.ini: the settings.ini file required by MAJIQ build, including the list of majiq_groups and samples
  -- _version.yaml containing software version information gathered at run-time, emitted as `version`
*/

process GET_MAJIQ_SETTINGS {

    input:
    path(samplesheetnextflow)
    path(majiq_contrasts)
    val(genome_identifier)

    output:
    path 'majiq_settings.ini', emit: majiq_settings
    path 'voila_view_cmds.txt', emit: voila_view_cmds
    path '_version.yaml', emit: version

    script:
    ensembl2ucsc = [
      'GRCh38': 'GRCh38',
      'GRCm39': 'GRCm39',
      'mRatBN7.2': 'mRatBN7.2',
      'mfas50': 'macFas5',
      'mfas60': 'macFas6'
    ]
    
    ucsc_genome = ensembl2ucsc[genome_identifier]
    if (ucsc_genome == null) {
      ucsc_genome = 'not_found'
    }
    
     
    """
    ${workflow.projectDir}/bin/get_majiq_settings.py --samplesheetnextflow $samplesheetnextflow --majiqcontrasts $majiq_contrasts --genome $ucsc_genome

    cat <<-END_VERSION > _version.yaml
    "${task.process}":
        get_majiq_settings.py: \$(echo \$(get_majiq_settings.py --version) | sed 's/get_majiq_settings.py //g')
        python: \$(python --version 2>&1 | sed -nre 's/^[^0-9]*([0-9]+\\.[0-9]+(\\.[0-9]+)?)/\\1/p')
    END_VERSION
    """
}   
